config/routes.rb
Rails.application.routes.draw do
  

 

  resources :words do
    resources :meanings
    resources :examples 
  end

  root 'words#main'

end

app/models/example.rb
class Example < ActiveRecord::Base
	belongs_to :meaning
end

app/models/meaning.rb
class Meaning < ActiveRecord::Base
	belongs_to :word
#TODO make sure meaning when created can be entered only once
#TODO count meaning number for users
#meaning cannot be zero validates_numericality_of :meaning_number, :greater_than_or_equal_to => 1
	# def create_with_numbers(attr) #bring in the meaning attributes passed in from the form
	# 	meaning_number = meaning.try(&:meaning_number) || 1
	# 	@meaning = word
	# 	# meaning.meaning_number = meaning.meaning_number(:try) + 1
	# 	return meaning
	# end


end

app/models/word.rb
class Word < ActiveRecord::Base
	has_many :meanings, dependent: :destroy
	accepts_nested_attributes_for :meanings

	validates_presence_of :term, :origin, :pronunciation
	validates_length_of :term, :origin, :pronunciation, :minimum => 3
	validates_uniqueness_of :term
	
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	has_attached_file :audio
	validates_attachment_content_type :audio, :content_type => ['audio/mp3','audio/mpeg', 'audio/ogg', 'audio/wav']

	# def self.search(search)
  		# search_condition = "%" + search + "%"
  		# find(:all, :conditions => ['title LIKE ? OR description LIKE ?', search_condition, search_condition])
	# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  before_action :set_example, only: [:show, :edit, :update, :destroy]

  # GET /examples
  # GET /examples.json
  def index
    @examples = Example.all
  end

  # GET /examples/1
  # GET /examples/1.json
  def show
  end

  # GET /examples/new
  def new
    @example = Example.new
  end

  # GET /examples/1/edit
  def edit
  end

  # POST /examples
  # POST /examples.json
  def create
<<<<<<< HEAD
    @meaning = Meaning.find(params[:meaning_id])
    @example = @meaning.examples.create(example_params)

    if @example.save
     redirect_to edit_word_meaning_path(@meaning)
    end
    # respond_to do |format|
    #   if @example.save
    #     format.html { redirect_to @word, notice: 'Example was successfully created.' }
    #     format.json { render :show, status: :created, location: @word }
    #   else
    #     format.html { render :create }
    #     format.json { render json: @word.errors, status: :unprocessable_entity }
    #   end
    # end
=======
    @example = Example.new(example_params)

    respond_to do |format|
      if @example.save
        format.html { redirect_to @example, notice: 'Example was successfully created.' }
        format.json { render :show, status: :created, location: @example }
      else
        format.html { render :new }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
>>>>>>> 0160b3998bdbb91f61132a6a7e25027749953745
  end

  # PATCH/PUT /examples/1
  # PATCH/PUT /examples/1.json
  def update
    respond_to do |format|
      if @example.update(example_params)
        format.html { redirect_to @example, notice: 'Example was successfully updated.' }
        format.json { render :show, status: :ok, location: @example }
      else
        format.html { render :edit }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /examples/1
  # DELETE /examples/1.json
  def destroy
    @example.destroy
    respond_to do |format|
      format.html { redirect_to examples_url, notice: 'Example was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_example
      @example = Example.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def example_params
<<<<<<< HEAD
      params.require(:example).permit(:body, :source, :meaning_id)
=======
      params.require(:example).permit(:body, :source)
>>>>>>> 0160b3998bdbb91f61132a6a7e25027749953745
    end
end

app/controllers/meanings_controller.rb
class MeaningsController < ApplicationController
  before_action :set_meaning, only: [:show, :edit, :update, :destroy]
  before_action :set_word
  def index
    @meanings = Meaning.all
  end

  

  def show
  end

  def new
    @meaning = Meaning.new
  end

  def edit
  end

  def create
    if @word.meanings.first.nil?
      @meaning = @word.meanings.build(meaning_params)   #new
      @meaning.meaning_number = 1 #set it number to 1
      @meaning.save #save it

    else
      @meaning = @word.meanings.build(meaning_params)   #new
      @meaning.meaning_number = @word.meanings.order(:meaning_number => :asc).last.meaning_number + 1 #set it number to 1
      @meaning.save #save it
    end

    redirect_to edit_word_path(@word)
  end

  def update
      if @meaning.update(meaning_params)
       redirect_to edit_word_path(@word)
      end
  end

  def destroy
    @meaning.destroy

    redirect_to word_path(@word)
  end

  private
    def set_meaning
      @meaning = Meaning.find(params[:id])
    end

    def set_word
      @word = Word.find(params[:word_id])
    end


    def meaning_params
      params.require(:meaning).permit(:meaning_number, :part_of_speech, :definition, :context, :word_id)
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]
  layout 'main'
  

  # GET /words
  # GET /words.json
  def index
    @words = Word.where("term Like ?", "%#{params[:search]}%")
  end

  def main
    @words = Word.all
    @words = Word.where("term Like ?", "%#{params[:search]}%")
  end

  def wording
    
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # def self.search(search)
    # search_condition = "%" + search + "%"
    # Words.where(conditions: ["title LIKE ? OR description LIKE ?", search_condition])
  # end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:term, :pronunciation, :origin, :image, :audio, meanings_attributes: [:id, :meaning_number, :part_of_speech, :definition, :context])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/meanings_helper.rb
module MeaningsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/examples/_form.html.erb
<<<<<<< HEAD
<%= form_for([@meaning, @meaning.examples.build]) do |f| %>
=======
<%= form_for(@example) do |f| %>
  <% if @example.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@example.errors.count, "error") %> prohibited this example from being saved:</h2>

      <ul>
      <% @example.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
>>>>>>> 0160b3998bdbb91f61132a6a7e25027749953745

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_area :source %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/examples/edit.html.erb
<h1>Editing example</h1>

<%= render 'form' %>

<%= link_to 'Show', @example %> |
<%= link_to 'Back', examples_path %>

app/views/examples/index.html.erb
<h1>Listing examples</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Source</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @examples.each do |example| %>
      <tr>
        <td><%= example.body %></td>
        <td><%= example.source %></td>
        <td><%= link_to 'Show', example %></td>
        <td><%= link_to 'Edit', edit_example_path(example) %></td>
        <td><%= link_to 'Destroy', example, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Example', new_example_path %>

app/views/examples/new.html.erb
<h1>New example</h1>

<%= render 'form' %>

<%= link_to 'Back', examples_path %>

app/views/examples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @example.body %>
</p>

<p>
  <strong>Source:</strong>
  <%= @example.source %>
</p>

<%= link_to 'Edit', edit_example_path(@example) %> |
<%= link_to 'Back', examples_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pidict</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>PIDICT</title>
    <%= stylesheet_link_tag('application')%>
    <%= javascript_include_tag('application')%>


</head>
    <body>
        <!-- nav bar -->
            <nav class="navedit navbar navbar-default" role="navigation">
              <div class=" container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="/", style="color:white;">PIDICT</a>
                </div>

              <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="navedit_content nav navbar-nav">
                    <li><a href="#" style="color:white">about<span class="sr-only">(current)</span></a></li>
                    <li><a href="#" style="color:white">contact us</a></li>
                  </ul> 
                </div><!-- /.navbar-collapse -->
              </div><!-- /.container-fluid -->
            </nav>
        <!-- end of nav bar -->
        <div class="container" style="background">
             <%= yield %>
        </div>
        <!-- content and yield -->

    </body>
</html>

app/views/meanings/_form.html.erb
<%= form_for([@word, @word.meanings.build]) do |f| %>
 

  <div class="field">
    <%= f.label :meaning_number %><br>
    <%= f.number_field :meaning_number %>
  </div>
  <div class="field">
    <%= f.label :part_of_speech %><br>
    <%= f.text_field :part_of_speech %>
  </div>
  <div class="field">
    <%= f.label :definition %><br>
    <%= f.text_area :definition %>
  </div>
   <div class="field">
    <%= f.label :context %><br>
    <%= f.text_area :context %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meanings/_form2.html.erb
<%= form_for ([@word, @meaning]) do |f| %>

  <div class="field">
    <%= f.label :meaning_number %><br>
    <%= f.number_field :meaning_number %>
  </div>
  <div class="field">
    <%= f.label :part_of_speech %><br>
    <%= f.text_field :part_of_speech %>
  </div>
  <div class="field">
    <%= f.label :definition %><br>
    <%= f.text_area :definition %>
  </div>
   <div class="field">
    <%= f.label :context %><br>
    <%= f.text_area :context %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meanings/edit.html.erb
<h1>Editing meaning</h1>
<div class="jumbotron"> 
	
<%= render 'form2' %>

</div>

app/views/meanings/index.html.erb
<h1>Listing meanings</h1>

<table>
  <thead>
    <tr>
      <th>Meaning number</th>
      <th>Part of speech</th>
      <th>Definition</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meanings.each do |meaning| %>
      <tr>
        <td><%= meaning.meaning_number %></td>
        <td><%= meaning.part_of_speech %></td>
        <td><%= meaning.definition %></td>
        
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/meanings/new.html.erb
<h1>New meaning</h1>

<%= render 'form' %>

<%= link_to 'Back', meanings_path %>

app/views/meanings/show.html.erb
<h1>show</h1>

app/views/words/_form.html.erb
<%= form_for @word, :html => {:multipart => true} do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :term %><br>
    <%= f.text_field :term %>
  </div>
  <div class="field">
    <%= f.label :pronunciation %><br>
    <%= f.text_field :pronunciation %>
  </div>
<!-- adding sound for pronunciation -->
  <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>

  <!-- for image and file fields -->
   <div>
    <%= f.label :audio %>
    <%= f.file_field :audio %>
  </div><br>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/words/edit.html.erb
<h1>Editing word</h1>



<div class="container">
	<div class="row">
	<!-- columns for words -->
		<div class="jumbotron col-md-3" style="margin-right:2px;">
			<h1>Word</h1>
			<%= image_tag @word.image.url(:thumb), :alt => "" %>

			<%= render 'form' %>
		</div> <!-- end of words column -->

	<!-- columns for meanings -->
		<div class="jumbotron col-md-4" style="margin-right:2px;">
			<div>
				<h1>meaning</h1>
				<%= render "meanings/form" %>
			</div>



	<div class="row">
			<div class="jumbotron">
				<% @word.meanings.each do |meaning|%>
					<table class="table table-responsive">
							<tbody>
								<tr>
									<td>
										<%= meaning.meaning_number %>
									</td>
									<td>
										<%= meaning.definition %>
									</td>
									<td>
										<%= meaning.context %>
									</td>
									<td><%= link_to 'editor' %></td>
									<td>
										<%= link_to 'delete', [meaning.word, meaning], method: :delete, data: {confirm: 'are you sure?'}  %>
									</td>
								</tr>
							</tbody>
						</table>
					<% end %>
			</div>
		</div>
	</div> <!-- end of meanings column -->

		<!-- editing meaning column -->
		<div class="jumbotron col-md-4" style="margin-right:2px;">

		<!-- end of editing meaning column -->
	</div>
</div>


<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<h1>Listing words</h1>
<!-- <div class="bar bar-header item-input-inset">
<label class="item-input-wrapper">
<i class="icon ion-ios7-search placeholder-icon"></i>
<input type="search" placeholder="Search">
</label>
<button class="button button-clear">
search
</button>
</div> -->


<form class="bs-example bs-example-form" role="form">
    <div class="row">
      <div class="col-md-offset-9">
        <div class="input-group">
          <%= form_tag url: 'problems', method: :get do %>
            <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "search"%>
              <span class="input-group-btn">
                  <%= submit_tag "Search", class: "btn btn-default" %>
                <% end %>
              </span> 
        </div>
      </div>
   </div>
</form>
</div>


<table>
<thead>
<tr>
<th>Term</th>
<th>Pronunciation</th>
<th>Origin</th>
<th colspan="3"></th>
</tr>
</thead>
<tbody>
<% @words.each do |word| %>
<tr>
<td><%= word.term %></td>
<td><%= word.pronunciation %></td>
<td><%= word.origin %></td>
<td><%= link_to 'Show', word %></td>
<td><%= link_to 'Edit', edit_word_path(word) %></td>
<td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<td><%= image_tag word.image.url(:thumb), :alt => "" %></td>
</tr>
<% end %>
</tbody>
</table>
<br>
<%= link_to 'New Word', new_word_path %>

app/views/words/main.html.erb
<!-- search button at the center -->
	
<form class="form-wrapper">
    <input type="text" id="search">
    <input type="submit" value="search" id="submit">
</form>





<div class="container">
	
	

	<div class="row col-md-12">
	</div>

	<div class="col-md-4 cards cright">
			
	</div>
		
	<div class="col-md-4 cards " style="margin:1 2% 1 2%">
			
	</div>
		
	<div class="col-md-4 cards cleft">
			
	</div>
	
	</div>
	

<!-- 
left card for trending word of the day
-->

<!-- middle card for about -->


<!-- right card for for how to use -->

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<div style="margin: 0 20% 0 10%">
	<div class="container megatron col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-1 col-xs-offset-8 col-xs-offset-1 ">
			<div class="worded">

				<div class="container face front">
						<div class="word row">
							<div class="col-md-8 col-xs-8 col-sm-8 col-md-offset-1 col-xs-offset-1 col-sm-offset-1 ">
								<h2><%= @word.term %></h2>
							</div>
						</div> <!-- end of word row -->

						<div class="row word_db">
							<div class="col-md-8 col-xs-7 col-sm-7">
								pronunciation:
								<h5>
									<%= @word.pronunciation %>
								</h5>
								originated from:
								<h5>
									<%= @word.origin %>
								</h5>
							</div>
						</div><!-- end or word db row -->

				</div> <!-- end of container -->

				<div class="face back">
					<div class="" style="margin-top:3px">
						<%= audio_tag @word.audio.url, controls: true, class: "audio-player"%>
					</div>

					<div class="container">
					<% @word.meanings.each do |meaning| %>
						<div class="meaning_card">
							<div class="container">
								<div class="row">
									<div class="col-md-1 col-sm-1 col-xs-1" >
										<span class="badge"><%= meaning.meaning_number %></span>
									</div>
									<div class="col-md-4 col-sm-6 col-xs-6  col-xs-offset 1"><%= meaning.part_of_speech %></div>
								</div>

								<div class="conatiner">
									<div class="row define">
										<div class=""> <%= meaning.definition %> </div>
									</div>
									<div class="row">

										<div class=" well well-sm"> <span><em><strong> usage: </strong></em></span><%= meaning.context %> </div> 
									</div>
								</div>
							</div>

								<!-- examples -->
								
								<!-- more examples -->
									<div class="btn-group example">
										  <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
										    More Examples <span class="caret"></span>
										  </button>
										  <ul class="dropdown-menu" role="menu">
										    <li class="divider"></li>
										    <li><a href="#">examples would be here</a></li>
										  </ul>
										</div>
									<p><td><%= link_to 'editor', edit_word_meaning_path(meaning.word, meaning)  %></td></p>
							<% end %>
						</div>
					</div>



					<!-- Single button -->


				</div>

		 	</div>
	</div>
</div>

app/views/words/wording.html.erb
<p id="notice"><%= notice %></p>



	<div class="container">
		<div class="row">
			<div class="term col-md-4 col-sm-5 col-xs-5">
				<strong>Term:</strong>
				<h2><%= @word.term %></h2> 
		        <p>
					<strong>Pronunciation:</strong>
					<%= @word.pronunciation %>
				</p>
				<p>
					<strong>Origin:</strong>
					<%= @word.origin %>
				</p>
			</div>

			<div class="col-md-offset-1 col-md-1 col-sm-2 col-xs-2" style="margin:2px;">
			<%= link_to(image_tag('speaker.png', :class => "pronounce")) %>
			</div>

			<div class="col-md-2 col-sm-4 col-xs-4">
					<p>
					<%= image_tag @word.image.url(:thumb), :alt => "" %>
					</p>
			</div>

		</div>

		<div class="row">
			<div class="jumbotron col-md-11">
				<% @word.meanings.each do |meaning|%>
					<table class="table table-responsive">
							<tbody>
								<tr>
									<td>
										<%= meaning.meaning_number %>
									</td>
									<td>
										<%= meaning.definition %>
									</td>
									<td>
										<%= meaning.context %>
									</td>
									<td><%= link_to 'editor', edit_word_meaning_path(meaning.word, meaning)  %></td>
									<td>
										<%= link_to 'delete', [meaning.word, meaning], method: :delete, data: {confirm: 'are you sure?'}  %>
									</td>
								</tr>
							</tbody>
						</table>
					<% end %>
			</div>
		</div>
		
	</div>








<%= link_to 'Edit', edit_word_path(@word) %> 
<%= link_to 'Back', words_path %>